---
## RPMFusion Repos
- name: add rpmfusion free and non-free repository
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ dnf_releasever }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ dnf_releasever }}.noarch.rpm"
  become: true

- name: add rpmfusion signature keys
  rpm_key:
    state: present
    key: "{{ item }}"
  become: true
  with_fileglob:
    - "/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-*"

## Adobe Repos
- name: add Adobe repository
  dnf:
    name: "http://linuxdownload.adobe.com/adobe-release/adobe-release-{{ dnf_basearch }}-1.0-1.noarch.rpm"
    state: present
  become: true

- name: add Adobe signature key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
  become: true

## Google Repos
- name: add Google repositories
  yum_repository:
    state: present
    file: /etc/yum.repos.d/google-{{ dnf_basearch }}
    name: google-chrome-{{ item }}
    description: Google {{ item }} - $basearch
    baseurl: http://dl.google.com/linux/{{ item }}/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub  
  become: true
  with_items:
      - earth
      - chrome
      - mod-pagespeed

- name: enable fedora-cisco-openh264
  command: dnf config-manager --set-enabled fedora-cisco-openh264
  become: true

#- name: enable fedora-cisco-openh264
#  yum_repository:
#    state: present
#    file: /etc/yum.repos.d/fedora-cisco-openh264
#    name: fedora-cisco-openh264
#    description: Fedora $releasever openh264 (From Cisco) - $basearch
#    baseurl: https://codecs.fedoraproject.org/openh264/$releasever/$basearch
#    enabled: yes
#  become: true

