---
- name: Create Firefox extension directory
  file:
    path: "{{ ansible_env.HOME }}/extensions"
    state: directory
    mode: 0755

- name: Install EFF Firefox plugins
  get_url:
    url: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.mozilla/firefox/extension"
  with_items:
    - https://www.eff.org/files/https-everywhere-latest.xpi
    - https://www.eff.org/files/privacy-badger-latest.xpi

- name: Uncompress files


# gksudo firefox -install-global-extension addon-1865-latest.xpi
# firefox -silent -install-global-extension addon-1865-latest.xpi -setDefaultBrowser www.google.es
## REF: https://askubuntu.com/questions/73474/how-to-install-firefox-addon-from-command-line-in-scripts

