---
- name: Selinux Enforcing
  selinux:
    policy: targeted
    state: encforcing
## check reboot_required ?

- name: Set (httpd_can_network_connect) flag on and keep it persistent
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  with_items:
    - { name: a_word_with_underscores, state: yes }

- name: Allow Apache to listen on tcp port 8888
  seport:
    ports: 8888
    proto: tcp
    setype: http_port_t
    state: present

- name: Allow apache to modify files in /srv/git_repos
  sefcontext:
    target: '/srv/git_repos(/.*)?'
    setype: httpd_git_rw_content_t
    state: present

