---
- name: Install bash
  dnf:
    name: bash
    state: present
  become: true
  when: ansible_distribution == 'Fedora'

- name: Install bash
  apt:
    name: bash
    state: present
  become: true
  when: ansible_distribution == 'Debian'

- name: Create ~/.profile.d directory
  file:
    path: "{{ ansible_env.HOME }}/.profile.d/"
    state: directory

- name: Add source ~/.profile.d in ~/.bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: present
    regexp: 'for file in $HOME/.profile.d/*; do source $file; done'
    line: 'for file in $HOME/.profile.d/*; do source $file; done'

  #blockinfile


- name: Add custom ~/.profile.d/
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.profile.d/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
  with_items:
    - alias

- name: Set bell-style to none
  lineinfile:
    path: /etc/inputrc
    state: present
    regexp: '^#?set bell-style'
    line: 'set bell-style none'
  become: yes

