---

- name: wpa_
  template: 
    src: wpa_supplicant.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    mode: 0600
    owner: root
  become: yes


#- name: Install prerequisites
#  apt:
#    name: "{{ item}}"
#	state: latest
#  with_items:
#    - network-manager


#- name: nmcli
#  nmcli:
#    conn_name: paradise-ac
#    state: present
#    ifname: 
#    ip4:
#    gw4:
#  when: ansible_distribution == 'Fedora'


#nmcli connection add \
# type wifi con-name "MySSID" ifname wlp3s0 ssid "MySSID" -- \
# wifi-sec.key-mgmt wpa-eap 802-1x.eap tls 802-1x.identity "USERNAME" \
# 802-1x.ca-cert ~/ca.pem 802-1x.client-cert ~/cert.pem \
# 802-1x.private-key-password "..." 802-1x.private-key ~/key.pem

