---
- name: Add ring repository
  command: dnf config-manager --add-repo https://dl.ring.cx/ring-nightly/fedora_26/ring-nightly.repo
  become: yes

- name: Install ring
  dnf:
    name: ring
    state: latest
  become: yes

## REF: https://ring.cx/

