---
- name: copy gpg.conf
  template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.gnupg/{{ item }}"
    user: "{{ ansible_env.USER }}"
    mode: 0640
    backup: yes
  with_fileglob:
    - gpg.conf
    - gpg-agent.conf

- name: copy GNUPG keys
  unarchive:
    src: "{{ role_path }}/files/gnupg-keys.tar.gz"
    dest: "{{ ansible_env.HOME }}/.gnupg/private-keys-v1.d/"
    keep_newer: yes
    decrypt: no
    user: "{{ ansible_env.USER }}"
    mode: 0600

