---

- name: Install motion prerequisites
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - ffmpeg
    - v4l-utils
    - libmariadbclient18
    - libpq5
  become: yes

- name: Install motion
  apt:
    deb:   'https://github.com/Motion-Project/motion/releases/download/release-4.1/pi_stretch_motion_4.1-1_armhf.deb'
    state:  present
  become: yes


- name: Install motioneye prerequisites
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-pip
    - python-dev
    - libssl-dev
    - libcurl4-openssl-dev
    - libjpeg-dev
  become: yes


- name: Install motioneye
  pip:
    name: motioneye
    state: latest
  become: yes


- name: Ensure motioneye directories
  file:
    name: "{{ item}}"
    state: directory
  with_items:
    - /etc/motioneye
    - /var/lib/motioneye
  become: yes

- name: Configuration
  copy:
    src: "/usr/local/share/motioneye/extra/motioneye.conf.sample"
    dest: "/etc/motioneye/motioneye.conf"
    remote_src: yes
  become: yes

- name: Copy systemd-unit
  copy:
    src: "/usr/local/share/motioneye/extra/motioneye.systemd-unit-local"
    dest: "/etc/systemd/system/motioneye.service"
    remote_src: yes
  become: yes


- name: Enable motioneye
  systemd:
    name: motioneye
    enabled: yes
    state: restarted
  become: yes



