---
- name: Install prerequisites
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - nfs-utils
    - libnfs-utils

- name: enable export directory
  lineinfile:
    path: /etc/exports
    regexp: '^/srv'
    line: '/srv *(rw,sec=krb5,krb5i,krb5p,no_root_squash)'
  with_items:
    - one for each line in exports

## Check for BTRFS specific options

- name: enable secure NFS
  lineinfile:
    path: /etc/sysconfig/nfs
    regexp: '^SECURE_NFS'
    line: 'SECURE_NFS="yes"'

- name: enable nfs server
  systemd:
    name: nfs.service
    enabled: yes
    state: started

- name: enable nfs-secure server
  systemd:
    name: nfs-secure.service
    enabled: yes
    state: started

