---
- name: Install password store package
  dnf:
    name: pass
    state: latest
  become: yes
  when: ansible_distribution == 'Fedora'

- name: Install password store package
  apt:
    name: pass
    state: latest
    update_cache: no
  become: yes
  when: ansible_distribution == 'Debian'

- name: copy password-store archive
  unarchive:
    src: "{{ role_path }}/files/password-store.tar.gz"
    dest: "{{ ansible_env.HOME }}/.password-store"
    keep_newer: yes
    decrypt: no
    user: "{{ ansible_env.USER }}"

