# https://savedlog.com/linux/aaa-server-freeipa-and-freeradius/
---
- name: FreeRadius Prerequisites
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - freeradius
    - freeradius-doc
    - freeradius-utils
    - freeradius-ldap
    - freeradius-krb5

- name: FreeRADIUS config
  template:
    src: "{{ item }}"
    dest: "{{ radius_dir }}/{{ item }}"
    mode: 0640
    owner: root
    group: radiusd
    backup: yes
  with_items:
    - clients
    - radiusd
  when: item.state == 'file'

# https://github.com/FreeRADIUS/freeradius-server/tree/v3.0.x/raddb
- name: FreeRADIUS modules
  template:
    src: "{{ item }}"
    dest: "{{ radius_dir }}/mods-available/{{ item }}"
    mode: 0640
    owner: root
    group: radiusd
    backup: yes
  with_filetree:
    - "{{ role_path }}/template/mods/*"
  when: item.state == 'file'

- name: enable FreeRadius
  systemd:
    name: radiusd
    enabled: yes
    state: started
  become: yes

