---
- name: create user ansible.cfg
  template:
    src: ansible.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config.d/ansible.cfg"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0600'
    backup: no

