---

- name: git repo
  git:
    repo: 'https://github.com/goodtft/LCD-show.git'
    dest: /home/pi/LCD-show/
    force: yes
    update: yes

- name: guarantee permission
  file:
    path: /home/pi/LCD-show/LCD35-show
    mode: '+x'
    owner: pi

- name: execute LCD-35-show
  shell: ./LCD35-show
  args:
    chdir: /home/pi/LCD-show/
    creates: /usr/share/X11/xorg.conf.d/99-fbturbo.conf
  become: yes


#- name: return to  normal
#  shell: ./LCD-hdmi
#  args:
#    chdir: /home/pi/LCD-show/
#    creates: /usr/share/X11/xorg.conf.d/99-fbturbo.conf
#  become: yes



