---
- name: Install vim
  dnf:
    name: vim
    state: latest
  become: yes

- name: Ensure pack directory
  file:
    path: "{{ ansible_env.HOME }}/.vim/pack"
    state: directory

#- name: Install Vundle
#  git:
#    repo: https://github.com/VundleVim/Vundle.vim.git
#    dest: ~/.vim/bundle/Vundle.vim

## https://shapeshed.com/vim-packages/

- name: Change .vimrc
  template:
    src: vimrc.tpl
    dest: "{{ ansible_env.HOME }}/.vimrc"
    force: yes
    backup: yes
    user: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

#- name: install vim bundles
#  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
#  ignore_errors: yes

