---
#- name: install the 'Development tools' package group
#  dnf:
#    name: '@Development tools'
#    state: present
#  become: true

- name: install essential packages
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - tmux
    - vim
    - git
    - pass
    - gnupg

- name: install media packages
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - texlive-scheme-basic
    - openh264
    - mozilla-openh264
    - google-chrome-stable
    - gstreamer1-plugin-openh264
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
    - gstreamer1-plugins-ugly-free
    - gstreamer1-plugins-bad-nonfree
    - gstreamer1-plugins-bad-free
    - flash-plugin
    - mplayer
    - vlc
    - transmission
    - entangle
    - darktable
    - gimp
    - luminance-hdr
    - argyllcms
    - calibre

